site:
  title: Master CSMI::Stages 2021
  url: https://master-csmi.github.io/csmi-stages-2021
  start_page: csmi-stages-2021:ROOT:index.adoc
content:
  sources:
  - url: https://github.com/master-csmi/csmi-stages-2021
    branches: main
ui:
  bundle:
    url: https://gitlab.com/feelpp/antora-ui-default/-/jobs/artifacts/feelpp/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  clean: true
  dir: public
  
asciidoc:
  attributes:
    project_version: 0.1
    deploymentRoot: ""
    numbered: true
    allow-uri-read: true
    hide-uri-scheme: true
    year: 2021
    feelpp: Feel++
    angiotk: AngioTK
    4fastsim: 4FastSim
    stem: latexmath
    hemotumpp: Hemotum++
    eye2brain: Eye2Brain
    swimmer: Swimmer
    cemosis: https://www.cemosis.fr[Cemosis]
    amies: https://www.agence-maths-entreprises.fr/[AMIES]
  extensions:
    - ./lib/tabs-block
    - "@djencks/asciidoctor-template"